<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use database\seeders\BilleteSeeder;
use App\Models\Billete;

class BilleteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $billetesData = [
            // Aquí irían al menos 50 entradas de billetes.
            // Ejemplo:
            [
                'nombre' => 'Dólar Estadounidense',
                'pais' => 'Estados Unidos',
                'denominacion' => '1',
                'anho_emision' => '2013',
                'imagen' => 'imagenes/usa_1_dollar.jpg',
                'descripcion' => 'Billete de un dólar estadounidense, con el retrato de George Washington.',
                'material' => 'Algodón y lino',
            ],
            [
                'nombre' => 'Euro',
                'pais' => 'Unión Europea',
                'denominacion' => '5',
                'anho_emision' => '2013',
                'imagen' => 'imagenes/eu_5_euro.jpg',
                'descripcion' => 'Billete de 5 euros, con un diseño arquitectónico de estilo clásico.',
                'material' => 'Algodón puro',
            ],
            [
                'nombre' => 'Yen Japonés',
                'pais' => 'Japón',
                'denominacion' => '1000',
                'anho_emision' => '2004',
                'imagen' => 'imagenes/jp_1000_yen.jpg',
                'descripcion' => 'Billete de 1000 yenes japoneses, con el retrato de Hideyo Noguchi.',
                'material' => 'Papel',
            ],
            [
                'nombre' => 'Libra Esterlina',
                'pais' => 'Reino Unido',
                'denominacion' => '20',
                'anho_emision' => '2020',
                'imagen' => 'imagenes/uk_20_pounds.jpg',
                'descripcion' => 'Billete de 20 libras con el retrato de J.M.W. Turner.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Franco Suizo',
                'pais' => 'Suiza',
                'denominacion' => '50',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/ch_50_francs.jpg',
                'descripcion' => 'Billete de 50 francos suizos con diseño temático de la naturaleza.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Canadiense',
                'pais' => 'Canadá',
                'denominacion' => '10',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/ca_10_dollars.jpg',
                'descripcion' => 'Billete de 10 dólares canadienses con el retrato de Viola Desmond.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Mexicano',
                'pais' => 'México',
                'denominacion' => '500',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/mx_500_pesos.jpg',
                'descripcion' => 'Billete de 500 pesos con los retratos de Benito Juárez y Diego Rivera.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Real Brasileño',
                'pais' => 'Brasil',
                'denominacion' => '100',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/br_100_reais.jpg',
                'descripcion' => 'Billete de 100 reales con la imagen de un pez mero.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Chileno',
                'pais' => 'Chile',
                'denominacion' => '2000',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/cl_2000_pesos.jpg',
                'descripcion' => 'Billete de 2000 pesos con el retrato de Manuel Rodríguez.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Sol Peruano',
                'pais' => 'Perú',
                'denominacion' => '50',
                'anho_emision' => '2021',
                'imagen' => 'imagenes/pe_50_soles.jpg',
                'descripcion' => 'Billete de 50 soles con el retrato de María Rostworowski.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Colombiano',
                'pais' => 'Colombia',
                'denominacion' => '2000',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/co_2000_pesos.jpg',
                'descripcion' => 'Billete de 2000 pesos con el retrato de Débora Arango.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Guaraní Paraguayo',
                'pais' => 'Paraguay',
                'denominacion' => '5000',
                'anho_emision' => '2011',
                'imagen' => 'imagenes/py_5000_guaranies.jpg',
                'descripcion' => 'Billete de 5000 guaraníes con la imagen de José Gaspar Rodríguez de Francia.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Uruguayo',
                'pais' => 'Uruguay',
                'denominacion' => '100',
                'anho_emision' => '2017',
                'imagen' => 'imagenes/uy_100_pesos.jpg',
                'descripcion' => 'Billete de 100 pesos con el retrato de Eduardo Fabini.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Cubano',
                'pais' => 'Cuba',
                'denominacion' => '20',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/cu_20_pesos.jpg',
                'descripcion' => 'Billete de 20 pesos con la imagen de Camilo Cienfuegos.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Dominicano',
                'pais' => 'República Dominicana',
                'denominacion' => '200',
                'anho_emision' => '2014',
                'imagen' => 'imagenes/do_200_pesos.jpg',
                'descripcion' => 'Billete de 200 pesos con la imagen de Juan Pablo Duarte.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Córdoba Nicaragüense',
                'pais' => 'Nicaragua',
                'denominacion' => '100',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/ni_100_cordobas.jpg',
                'descripcion' => 'Billete de 100 córdobas con la imagen de Rubén Darío.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Lempira Hondureño',
                'pais' => 'Honduras',
                'denominacion' => '50',
                'anho_emision' => '2012',
                'imagen' => 'imagenes/hn_50_lempiras.jpg',
                'descripcion' => 'Billete de 50 lempiras con la imagen de José Trinidad Cabañas.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Quetzal Guatemalteco',
                'pais' => 'Guatemala',
                'denominacion' => '20',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/gt_20_quetzales.jpg',
                'descripcion' => 'Billete de 20 quetzales con la imagen de Mariano Gálvez.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Balboa Panameño',
                'pais' => 'Panamá',
                'denominacion' => '1',
                'anho_emision' => '2011',
                'imagen' => 'imagenes/pa_1_balboa.jpg',
                'descripcion' => 'Billete conmemorativo de 1 balboa con la imagen de Vasco Núñez de Balboa.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Australiano',
                'pais' => 'Australia',
                'denominacion' => '50',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/au_50_dollars.jpg',
                'descripcion' => 'Billete de 50 dólares australianos con el retrato de David Unaipon.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Neozelandés',
                'pais' => 'Nueva Zelanda',
                'denominacion' => '20',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/nz_20_dollars.jpg',
                'descripcion' => 'Billete de 20 dólares neozelandeses con la imagen de la Reina Isabel II.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Yuan Chino',
                'pais' => 'China',
                'denominacion' => '100',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/cn_100_yuan.jpg',
                'descripcion' => 'Billete de 100 yuanes con el retrato de Mao Zedong.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Rupia India',
                'pais' => 'India',
                'denominacion' => '500',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/in_500_rupees.jpg',
                'descripcion' => 'Billete de 500 rupias con el retrato de Mahatma Gandhi.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Rupia Indonesia',
                'pais' => 'Indonesia',
                'denominacion' => '100000',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/id_100000_rupiah.jpg',
                'descripcion' => 'Billete de 100,000 rupias con los retratos de Soekarno y Mohammad Hatta.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Ringgit Malayo',
                'pais' => 'Malasia',
                'denominacion' => '50',
                'anho_emision' => '2012',
                'imagen' => 'imagenes/my_50_ringgit.jpg',
                'descripcion' => 'Billete de 50 ringgit con la imagen del primer ministro Tunku Abdul Rahman.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Baht Tailandés',
                'pais' => 'Tailandia',
                'denominacion' => '1000',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/th_1000_baht.jpg',
                'descripcion' => 'Billete de 1000 baht con el retrato del Rey Bhumibol Adulyadej.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Boliviano',
                'pais' => 'Bolivia',
                'denominacion' => '10',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/bo_10_bolivianos.jpg',
                'descripcion' => 'Billete de 10 Bolivianos de la nueva familia de billetes.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Argentino',
                'pais' => 'Argentina',
                'denominacion' => '50',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/ar_50_pesos.jpg',
                'descripcion' => 'Billete de 50 Pesos Argentinos con la imagen del Cóndor Andino.',
                'material' => 'Papel',
            ],
            [
                'nombre' => 'Dólar Estadounidense',
                'pais' => 'Estados Unidos',
                'denominacion' => '1',
                'anho_emision' => '2013',
                'imagen' => 'imagenes/usa_1_dollar.jpg',
                'descripcion' => 'Billete de un dólar estadounidense, con el retrato de George Washington.',
                'material' => 'Algodón y lino',
            ],
            [
                'nombre' => 'Euro',
                'pais' => 'Unión Europea',
                'denominacion' => '5',
                'anho_emision' => '2013',
                'imagen' => 'imagenes/eu_5_euro.jpg',
                'descripcion' => 'Billete de 5 euros, con un diseño arquitectónico de estilo clásico.',
                'material' => 'Algodón puro',
            ],
            [
                'nombre' => 'Yen Japonés',
                'pais' => 'Japón',
                'denominacion' => '1000',
                'anho_emision' => '2004',
                'imagen' => 'imagenes/jp_1000_yen.jpg',
                'descripcion' => 'Billete de 1000 yenes japoneses, con el retrato de Hideyo Noguchi.',
                'material' => 'Papel',
            ],
            [
                'nombre' => 'Libra Esterlina',
                'pais' => 'Reino Unido',
                'denominacion' => '20',
                'anho_emision' => '2020',
                'imagen' => 'imagenes/uk_20_pounds.jpg',
                'descripcion' => 'Billete de 20 libras con el retrato de J.M.W. Turner.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Franco Suizo',
                'pais' => 'Suiza',
                'denominacion' => '50',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/ch_50_francs.png',
                'descripcion' => 'Billete de 50 francos suizos con diseño temático de la naturaleza.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Canadiense',
                'pais' => 'Canadá',
                'denominacion' => '10',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/ca_10_dollars.jpg',
                'descripcion' => 'Billete de 10 dólares canadienses con el retrato de Viola Desmond.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Mexicano',
                'pais' => 'México',
                'denominacion' => '500',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/mx_500_pesos.jpg',
                'descripcion' => 'Billete de 500 pesos con los retratos de Benito Juárez y Diego Rivera.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Real Brasileño',
                'pais' => 'Brasil',
                'denominacion' => '100',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/br_100_reais.jpg',
                'descripcion' => 'Billete de 100 reales con la imagen de un pez mero.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Chileno',
                'pais' => 'Chile',
                'denominacion' => '2000',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/cl_2000_pesos.jpg',
                'descripcion' => 'Billete de 2000 pesos con el retrato de Manuel Rodríguez.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Sol Peruano',
                'pais' => 'Perú',
                'denominacion' => '50',
                'anho_emision' => '2021',
                'imagen' => 'imagenes/pe_50_soles.jpg',
                'descripcion' => 'Billete de 50 soles con el retrato de María Rostworowski.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Colombiano',
                'pais' => 'Colombia',
                'denominacion' => '2000',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/co_2000_pesos.jpg',
                'descripcion' => 'Billete de 2000 pesos con el retrato de Débora Arango.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Guaraní Paraguayo',
                'pais' => 'Paraguay',
                'denominacion' => '5000',
                'anho_emision' => '2011',
                'imagen' => 'imagenes/py_5000_guaranies.jpg',
                'descripcion' => 'Billete de 5000 guaraníes con la imagen de José Gaspar Rodríguez de Francia.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Uruguayo',
                'pais' => 'Uruguay',
                'denominacion' => '100',
                'anho_emision' => '2017',
                'imagen' => 'imagenes/uy_100_pesos.jpg',
                'descripcion' => 'Billete de 100 pesos con el retrato de Eduardo Fabini.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Peso Cubano',
                'pais' => 'Cuba',
                'denominacion' => '20',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/cu_20_pesos.jpg',
                'descripcion' => 'Billete de 20 pesos con la imagen de Camilo Cienfuegos.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Dominicano',
                'pais' => 'República Dominicana',
                'denominacion' => '200',
                'anho_emision' => '2014',
                'imagen' => 'imagenes/do_200_pesos.jpg',
                'descripcion' => 'Billete de 200 pesos con la imagen de Juan Pablo Duarte.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Córdoba Nicaragüense',
                'pais' => 'Nicaragua',
                'denominacion' => '100',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/ni_100_cordobas.jpg',
                'descripcion' => 'Billete de 100 córdobas con la imagen de Rubén Darío.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Lempira Hondureño',
                'pais' => 'Honduras',
                'denominacion' => '50',
                'anho_emision' => '2012',
                'imagen' => 'imagenes/hn_50_lempiras.jpg',
                'descripcion' => 'Billete de 50 lempiras con la imagen de José Trinidad Cabañas.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Quetzal Guatemalteco',
                'pais' => 'Guatemala',
                'denominacion' => '20',
                'anho_emision' => '2010',
                'imagen' => 'imagenes/gt_20_quetzales.jpg',
                'descripcion' => 'Billete de 20 quetzales con la imagen de Mariano Gálvez.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Balboa Panameño',
                'pais' => 'Panamá',
                'denominacion' => '1',
                'anho_emision' => '2011',
                'imagen' => 'imagenes/pa_1_balboa.jpg',
                'descripcion' => 'Billete conmemorativo de 1 balboa con la imagen de Vasco Núñez de Balboa.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Australiano',
                'pais' => 'Australia',
                'denominacion' => '50',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/au_50_dollars.jpg',
                'descripcion' => 'Billete de 50 dólares australianos con el retrato de David Unaipon.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Dólar Neozelandés',
                'pais' => 'Nueva Zelanda',
                'denominacion' => '20',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/nz_20_dollars.jpg',
                'descripcion' => 'Billete de 20 dólares neozelandeses con la imagen de la Reina Isabel II.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Yuan Chino',
                'pais' => 'China',
                'denominacion' => '100',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/cn_100_yuan.jpg',
                'descripcion' => 'Billete de 100 yuanes con el retrato de Mao Zedong.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Rupia India',
                'pais' => 'India',
                'denominacion' => '500',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/in_500_rupees.jpg',
                'descripcion' => 'Billete de 500 rupias con el retrato de Mahatma Gandhi.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Rupia Indonesia',
                'pais' => 'Indonesia',
                'denominacion' => '100000',
                'anho_emision' => '2016',
                'imagen' => 'imagenes/id_100000_rupiah.jpg',
                'descripcion' => 'Billete de 100,000 rupias con los retratos de Soekarno y Mohammad Hatta.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Ringgit Malayo',
                'pais' => 'Malasia',
                'denominacion' => '50',
                'anho_emision' => '2012',
                'imagen' => 'imagenes/my_50_ringgit.jpg',
                'descripcion' => 'Billete de 50 ringgit con la imagen del primer ministro Tunku Abdul Rahman.',
                'material' => 'Polímero',
            ],
            [
                'nombre' => 'Baht Tailandés',
                'pais' => 'Tailandia',
                'denominacion' => '1000',
                'anho_emision' => '2015',
                'imagen' => 'imagenes/th_1000_baht.jpg',
                'descripcion' => 'Billete de 1000 baht con el retrato del Rey Bhumibol Adulyadej.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Boliviano',
                'pais' => 'Bolivia',
                'denominacion' => '10',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/bo_10_bolivianos.jpg',
                'descripcion' => 'Billete de 10 Bolivianos de la nueva familia de billetes.',
                'material' => 'Algodón',
            ],
            [
                'nombre' => 'Peso Argentino',
                'pais' => 'Argentina',
                'denominacion' => '50',
                'anho_emision' => '2018',
                'imagen' => 'imagenes/ar_50_pesos.jpg',
                'descripcion' => 'Billete de 50 Pesos Argentinos con la imagen del Cóndor Andino.',
                'material' => 'Papel',
            ],
        ];

        foreach ($billetesData as $data) {
            Billete::create($data);
        }
    }
}