<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Billete; // Asegúrate de importar el modelo si usas DB

class BilleteController extends Controller
{
    /**
     * Muestra la lista de billetes.
     */
    public function index()
    {
        // Si usas base de datos:
        $billetes = Billete::all();

        // Si NO usas base de datos (descomenta esta sección y comenta la de DB):
        /*
        $billetes = [
            [
                'id' => 1,
                'nombre' => 'Dólar Estadounidense',
                'pais' => 'Estados Unidos',
                'denominacion' => '1',
                'anho_emision' => '2013',
                'imagen' => '/imagenes/usa_1_dollar.jpg',
                'descripcion' => 'Billete de un dólar estadounidense, con el retrato de George Washington.',
                'material' => 'Algodón y lino',
            ],
            [
                'id' => 2,
                'nombre' => 'Euro',
                'pais' => 'Unión Europea',
                'denominacion' => '5',
                'anho_emision' => '2013',
                'imagen' => '/imagenes/eu_5_euro.jpg',
                'descripcion' => 'Billete de 5 euros, con un diseño arquitectónico de estilo clásico.',
                'material' => 'Algodón puro',
            ],
            [
                'id' => 3,
                'nombre' => 'Yen Japonés',
                'pais' => 'Japón',
                'denominacion' => '1000',
                'anho_emision' => '2004',
                'imagen' => '/imagenes/jp_1000_yen.jpg',
                'descripcion' => 'Billete de 1000 yenes japoneses, con el retrato de Hideyo Noguchi.',
                'material' => 'Papel',
            ],
            [
                'id' => 4,
                'nombre' => 'Libra Esterlina',
                'pais' => 'Reino Unido',
                'denominacion' => '10',
                'anho_emision' => '2017',
                'imagen' => '/imagenes/uk_10_pounds.jpg',
                'descripcion' => 'Billete de 10 Libras Esterlinas con el retrato de Jane Austen.',
                'material' => 'Polímero',
            ],
            [
                'id' => 5,
                'nombre' => 'Franco Suizo',
                'pais' => 'Suiza',
                'denominacion' => '20',
                'anho_emision' => '2016',
                'imagen' => '/imagenes/ch_20_francs.jpg',
                'descripcion' => 'Billete de 20 Francos Suizos con el retrato de la juventud.',
                'material' => 'Papel',
            ],
            [
                'id' => 6,
                'nombre' => 'Dólar Canadiense',
                'pais' => 'Canadá',
                'denominacion' => '5',
                'anho_emision' => '2013',
                'imagen' => '/imagenes/ca_5_dollar.jpg',
                'descripcion' => 'Billete de 5 Dólares Canadienses con el retrato de Wilfrid Laurier.',
                'material' => 'Polímero',
            ],
            [
                'id' => 7,
                'nombre' => 'Dólar Australiano',
                'pais' => 'Australia',
                'denominacion' => '10',
                'anho_emision' => '2017',
                'imagen' => '/imagenes/au_10_dollar.jpg',
                'descripcion' => 'Billete de 10 Dólares Australianos con el retrato de A. B. "Banjo" Paterson.',
                'material' => 'Polímero',
            ],
            [
                'id' => 8,
                'nombre' => 'Peso Mexicano',
                'pais' => 'México',
                'denominacion' => '20',
                'anho_emision' => '2018',
                'imagen' => '/imagenes/mx_20_pesos.jpg',
                'descripcion' => 'Billete de 20 Pesos Mexicanos con el retrato de Benito Juárez.',
                'material' => 'Polímero',
            ],
            [
                'id' => 9,
                'nombre' => 'Real Brasileño',
                'pais' => 'Brasil',
                'denominacion' => '10',
                'anho_emision' => '2010',
                'imagen' => '/imagenes/br_10_reais.jpg',
                'descripcion' => 'Billete de 10 Reales Brasileños con la imagen de la República.',
                'material' => 'Papel',
            ],
            [
                'id' => 10,
                'nombre' => 'Rublo Ruso',
                'pais' => 'Rusia',
                'denominacion' => '100',
                'anho_emision' => '1997',
                'imagen' => '/imagenes/ru_100_rubles.jpg',
                'descripcion' => 'Billete de 100 Rublos Rusos con la imagen del Teatro Bolshói.',
                'material' => 'Papel',
            ],
            [
                'id' => 11,
                'nombre' => 'Rupia India',
                'pais' => 'India',
                'denominacion' => '100',
                'anho_emision' => '2018',
                'imagen' => '/imagenes/in_100_rupees.jpg',
                'descripcion' => 'Billete de 100 Rupias Indias con la imagen de Mahatma Gandhi.',
                'material' => 'Papel',
            ],
            [
                'id' => 12,
                'nombre' => 'Yuan Chino',
                'pais' => 'China',
                'denominacion' => '10',
                'anho_emision' => '1999',
                'imagen' => '/imagenes/cn_10_yuan.jpg',
                'descripcion' => 'Billete de 10 Yuanes Chinos con la imagen de Mao Zedong.',
                'material' => 'Papel',
            ],
            [
                'id' => 13,
                'nombre' => 'Rand Sudafricano',
                'pais' => 'Sudáfrica',
                'denominacion' => '10',
                'anho_emision' => '2012',
                'imagen' => '/imagenes/za_10_rand.jpg',
                'descripcion' => 'Billete de 10 Rands Sudafricanos con la imagen de Nelson Mandela.',
                'material' => 'Papel',
            ],
            [
                'id' => 14,
                'nombre' => 'Corona Sueca',
                'pais' => 'Suecia',
                'denominacion' => '20',
                'anho_emision' => '2015',
                'imagen' => '/imagenes/se_20_kronor.jpg',
                'descripcion' => 'Billete de 20 Coronas Suecas con el retrato de Astrid Lindgren.',
                'material' => 'Papel',
            ],
            [
                'id' => 15,
                'nombre' => 'Corona Noruega',
                'pais' => 'Noruega',
                'denominacion' => '50',
                'anho_emision' => '2017',
                'imagen' => '/imagenes/no_50_kroner.jpg',
                'descripcion' => 'Billete de 50 Coronas Noruegas con un diseño marítimo.',
                'material' => 'Papel',
            ],
            [
                'id' => 16,
                'nombre' => 'Peso Chileno',
                'pais' => 'Chile',
                'denominacion' => '1000',
                'anho_emision' => '2011',
                'imagen' => '/imagenes/cl_1000_pesos.jpg',
                'descripcion' => 'Billete de 1000 Pesos Chilenos con el retrato de Ignacio Carrera Pinto.',
                'material' => 'Polímero',
            ],
            [
                'id' => 17,
                'nombre' => 'Peso Colombiano',
                'pais' => 'Colombia',
                'denominacion' => '2000',
                'anho_emision' => '2016',
                'imagen' => '/imagenes/co_2000_pesos.jpg',
                'descripcion' => 'Billete de 2000 Pesos Colombianos con el retrato de Debora Arango.',
                'material' => 'Polímero',
            ],
            [
                'id' => 18,
                'nombre' => 'Sol Peruano',
                'pais' => 'Perú',
                'denominacion' => '10',
                'anho_emision' => '2014',
                'imagen' => '/imagenes/pe_10_soles.jpg',
                'descripcion' => 'Billete de 10 Soles Peruanos con el retrato de José Quiñones Gonzales.',
                'material' => 'Algodón',
            ],
            [
                'id' => 19,
                'nombre' => 'Guaraní Paraguayo',
                'pais' => 'Paraguay',
                'denominacion' => '2000',
                'anho_emision' => '2008',
                'imagen' => '/imagenes/py_2000_guaranies.jpg',
                'descripcion' => 'Billete de 2000 Guaraníes Paraguayos con el retrato de Adela Speratti.',
                'material' => 'Papel',
            ],
            [
                'id' => 20,
                'nombre' => 'Peso Uruguayo',
                'pais' => 'Uruguay',
                'denominacion' => '20',
                'anho_emision' => '2015',
                'imagen' => '/imagenes/uy_20_pesos.jpg',
                'descripcion' => 'Billete de 20 Pesos Uruguayos con el retrato de Juan Zorrilla de San Martín.',
                'material' => 'Papel',
            ],
            [
                'id' => 21,
                'nombre' => 'Shekel Israelí',
                'pais' => 'Israel',
                'denominacion' => '20',
                'anho_emision' => '2017',
                'imagen' => '/imagenes/il_20_shekel.jpg',
                'descripcion' => 'Billete de 20 Shekels Israelíes con el retrato de Rachel Bluwstein.',
                'material' => 'Polímero',
            ],
            [
                'id' => 22,
                'nombre' => 'Dinar Jordano',
                'pais' => 'Jordania',
                'denominacion' => '1',
                'anho_emision' => '2002',
                'imagen' => '/imagenes/jo_1_dinar.jpg',
                'descripcion' => 'Billete de 1 Dinar Jordano con el retrato de Rey Abdullah I.',
                'material' => 'Papel',
            ],
            [
                'id' => 23,
                'nombre' => 'Dirham Marroquí',
                'pais' => 'Marruecos',
                'denominacion' => '20',
                'anho_emision' => '2012',
                'imagen' => '/imagenes/ma_20_dirham.jpg',
                'descripcion' => 'Billete de 20 Dirhams Marroquíes con el retrato del Rey Mohammed VI.',
                'material' => 'Papel',
            ],
            [
                'id' => 24,
                'nombre' => 'Lira Turca',
                'pais' => 'Turquía',
                'denominacion' => '5',
                'anho_emision' => '2009',
                'imagen' => '/imagenes/tr_5_lira.jpg',
                'descripcion' => 'Billete de 5 Liras Turcas con el retrato de Mustafa Kemal Atatürk.',
                'material' => 'Papel',
            ],
            [
                'id' => 25,
                'nombre' => 'Corona Checa',
                'pais' => 'República Checa',
                'denominacion' => '100',
                'anho_emision' => '1997',
                'imagen' => '/imagenes/cz_100_korun.jpg',
                'descripcion' => 'Billete de 100 Coronas Checas con el retrato de Carlos IV.',
                'material' => 'Papel',
            ],
            [
                'id' => 26,
                'nombre' => 'Forint Húngaro',
                'pais' => 'Hungría',
                'denominacion' => '500',
                'anho_emision' => '1998',
                'imagen' => '/imagenes/hu_500_forint.jpg',
                'descripcion' => 'Billete de 500 Forints Húngaros con el retrato de Ferenc Rákóczi II.',
                'material' => 'Papel',
            ],
            [
                'id' => 27,
                'nombre' => 'Zloty Polaco',
                'pais' => 'Polonia',
                'denominacion' => '10',
                'anho_emision' => '2014',
                'imagen' => '/imagenes/pl_10_zloty.jpg',
                'descripcion' => 'Billete de 10 Zlotys Polacos con el retrato de Mieszko I.',
                'material' => 'Papel',
            ],
            [
                'id' => 28,
                'nombre' => 'Leu Rumano',
                'pais' => 'Rumania',
                'denominacion' => '1',
                'anho_emision' => '2005',
                'imagen' => '/imagenes/ro_1_leu.jpg',
                'descripcion' => 'Billete de 1 Leu Rumano con el retrato de Nicolae Iorga.',
                'material' => 'Polímero',
            ],
            [
                'id' => 29,
                'nombre' => 'Lev Búlgaro',
                'pais' => 'Bulgaria',
                'denominacion' => '2',
                'anho_emision' => '1999',
                'imagen' => '/imagenes/bg_2_leva.jpg',
                'descripcion' => 'Billete de 2 Leva Búlgaros con el retrato de Paisius de Hilendar.',
                'material' => 'Papel',
            ],
            [
                'id' => 30,
                'nombre' => 'Dinar Serbio',
                'pais' => 'Serbia',
                'denominacion' => '10',
                'anho_emision' => '2006',
                'imagen' => '/imagenes/rs_10_dinars.jpg',
                'descripcion' => 'Billete de 10 Dinares Serbios con el retrato de Vuk Karadžić.',
                'material' => 'Papel',
            ],
            [
                'id' => 31,
                'nombre' => 'Kuna Croata',
                'pais' => 'Croacia',
                'denominacion' => '10',
                'anho_emision' => '2001',
                'imagen' => '/imagenes/hr_10_kuna.jpg',
                'descripcion' => 'Billete de 10 Kuna Croatas con el retrato de Juraj Dobrila.',
                'material' => 'Papel',
            ],
            [
                'id' => 32,
                'nombre' => 'Marco Bosnio',
                'pais' => 'Bosnia y Herzegovina',
                'denominacion' => '10',
                'anho_emision' => '1998',
                'imagen' => '/imagenes/ba_10_marka.jpg',
                'descripcion' => 'Billete de 10 Marcas Bosnias con el retrato de Mehmedalija Mak Dizdar.',
                'material' => 'Papel',
            ],
            [
                'id' => 33,
                'nombre' => 'Manat Azerbaiyano',
                'pais' => 'Azerbaiyán',
                'denominacion' => '1',
                'anho_emision' => '2006',
                'imagen' => '/imagenes/az_1_manat.jpg',
                'descripcion' => 'Billete de 1 Manat Azerbaiyano con símbolos nacionales.',
                'material' => 'Papel',
            ],
            [
                'id' => 34,
                'nombre' => 'Tenge Kazajo',
                'pais' => 'Kazajistán',
                'denominacion' => '500',
                'anho_emision' => '2006',
                'imagen' => '/imagenes/kz_500_tenge.jpg',
                'descripcion' => 'Billete de 500 Tenge Kazajos con el retrato de Abay Qunanbayuli.',
                'material' => 'Papel',
            ],
            [
                'id' => 35,
                'nombre' => 'Rupia Indonesia',
                'pais' => 'Indonesia',
                'denominacion' => '1000',
                'anho_emision' => '2016',
                'imagen' => '/imagenes/id_1000_rupiah.jpg',
                'descripcion' => 'Billete de 1000 Rupias Indonesianas con el retrato de Cut Nyak Dien.',
                'material' => 'Papel',
            ],
            [
                'id' => 36,
                'nombre' => 'Baht Tailandés',
                'pais' => 'Tailandia',
                'denominacion' => '20',
                'anho_emision' => '2018',
                'imagen' => '/imagenes/th_20_baht.jpg',
                'descripcion' => 'Billete de 20 Baht Tailandeses con el retrato del Rey Vajiralongkorn.',
                'material' => 'Polímero',
            ],
            [
                'id' => 37,
                'nombre' => 'Ringgit Malayo',
                'pais' => 'Malasia',
                'denominacion' => '1',
                'anho_emision' => '2012',
                'imagen' => '/imagenes/my_1_ringgit.jpg',
                'descripcion' => 'Billete de 1 Ringgit Malayo con el retrato de Tuanku Abdul Rahman.',
                'material' => 'Polímero',
            ],
            [
                'id' => 38,
                'nombre' => 'Dólar de Singapur',
                'pais' => 'Singapur',
                'denominacion' => '2',
                'anho_emision' => '1999',
                'imagen' => '/imagenes/sg_2_dollar.jpg',
                'descripcion' => 'Billete de 2 Dólares de Singapur con el retrato de Yusof Ishak.',
                'material' => 'Polímero',
            ],
            [
                'id' => 39,
                'nombre' => 'Dólar de Hong Kong',
                'pais' => 'Hong Kong',
                'denominacion' => '20',
                'anho_emision' => '2010',
                'imagen' => '/imagenes/hk_20_dollar.jpg',
                'descripcion' => 'Billete de 20 Dólares de Hong Kong con un diseño genérico.',
                'material' => 'Papel',
            ],
            [
                'id' => 40,
                'nombre' => 'Won Surcoreano',
                'pais' => 'Corea del Sur',
                'denominacion' => '1000',
                'anho_emision' => '2007',
                'imagen' => '/imagenes/kr_1000_won.jpg',
                'descripcion' => 'Billete de 1000 Won Surcoreanos con el retrato de Yi Hwang.',
                'material' => 'Papel',
            ],
            [
                'id' => 41,
                'nombre' => 'Dólar Neozelandés',
                'pais' => 'Nueva Zelanda',
                'denominacion' => '5',
                'anho_emision' => '2015',
                'imagen' => '/imagenes/nz_5_dollar.jpg',
                'descripcion' => 'Billete de 5 Dólares Neozelandeses con el retrato de Sir Edmund Hillary.',
                'material' => 'Polímero',
            ],
            [
                'id' => 42,
                'nombre' => 'Peso Filipino',
                'pais' => 'Filipinas',
                'denominacion' => '20',
                'anho_emision' => '2010',
                'imagen' => '/imagenes/ph_20_pesos.jpg',
                'descripcion' => 'Billete de 20 Pesos Filipinos con el retrato de Manuel L. Quezon.',
                'material' => 'Papel',
            ],
            [
                'id' => 43,
                'nombre' => 'Riyal Saudí',
                'pais' => 'Arabia Saudita',
                'denominacion' => '5',
                'anho_emision' => '2016',
                'imagen' => '/imagenes/sa_5_riyal.jpg',
                'descripcion' => 'Billete de 5 Riyales Saudíes con el retrato del Rey Salman bin Abdulaziz Al Saud.',
                'material' => 'Polímero',
            ],
            [
                'id' => 44,
                'nombre' => 'Dinar Kuwaítí',
                'pais' => 'Kuwait',
                'denominacion' => '1/4',
                'anho_emision' => '2014',
                'imagen' => '/imagenes/kw_0_25_dinar.jpg',
                'descripcion' => 'Billete de 1/4 Dinar Kuwaítí con puntos de referencia kuwaitíes.',
                'material' => 'Polímero',
            ],
            [
                'id' => 45,
                'nombre' => 'Dírham de los Emiratos Árabes Unidos',
                'pais' => 'Emiratos Árabes Unidos',
                'denominacion' => '5',
                'anho_emision' => '2014',
                'imagen' => '/imagenes/ae_5_dirham.jpg',
                'descripcion' => 'Billete de 5 Dírham de los Emiratos Árabes Unidos con el retrato de Sheikh Zayed bin Sultan Al Nahyan.',
                'material' => 'Polímero',
            ],
            [
                'id' => 46,
                'nombre' => 'Riyal Qatarí',
                'pais' => 'Qatar',
                'denominacion' => '1',
                'anho_emision' => '2020',
                'imagen' => '/imagenes/qa_1_riyal.jpg',
                'descripcion' => 'Billete de 1 Riyal Qatarí con el retrato del Emir Tamim bin Hamad Al Thani.',
                'material' => 'Polímero',
            ],
            [
                'id' => 47,
                'nombre' => 'Dólar de Taiwán',
                'pais' => 'Taiwán',
                'denominacion' => '100',
                'anho_emision' => '2000',
                'imagen' => '/imagenes/tw_100_dollar.jpg',
                'descripcion' => 'Billete de 100 Dólares de Taiwán con el retrato de Sun Yat-sen.',
                'material' => 'Papel',
            ],
            [
                'id' => 48,
                'nombre' => 'Dong Vietnamita',
                'pais' => 'Vietnam',
                'denominacion' => '10000',
                'anho_emision' => '2006',
                'imagen' => '/imagenes/vn_10000_dong.jpg',
                'descripcion' => 'Billete de 10000 Dong Vietnamitas con el retrato de Ho Chi Minh.',
                'material' => 'Polímero',
            ],
            [
                'id' => 49,
                'nombre' => 'Rupia de Sri Lanka',
                'pais' => 'Sri Lanka',
                'denominacion' => '20',
                'anho_emision' => '2017',
                'imagen' => '/imagenes/lk_20_rupees.jpg',
                'descripcion' => 'Billete de 20 Rupias de Sri Lanka con fauna y flora local.',
                'material' => 'Papel',
            ],
            [
                'id' => 50,
                'nombre' => 'Lari Georgiano',
                'pais' => 'Georgia',
                'denominacion' => '10',
                'anho_emision' => '2016',
                'imagen' => '/imagenes/ge_10_lari.jpg',
                'descripcion' => 'Billete de 10 Lari Georgianos con el retrato de Akaki Tsereteli.',
                'material' => 'Polímero',
            ],
            // Puedes añadir más billetes aquí para exceder los 50.
        ];
        */

        return view('billetes.index', compact('billetes'));
    }

    /**
     * Muestra los detalles de un billete específico.
     */
    public function show($id)
    {
        // Si usas base de datos:
        $billete = Billete::findOrFail($id);

        // Si NO usas base de datos (descomenta esta sección y comenta la de DB):
        /*
        $billete = collect($this->billetes)->firstWhere('id', $id);
        if (!$billete) {
            abort(404);
        }
        */

        return view('billetes.show', compact('billete'));
    }
}